### ISSUE TITLE
Question about the workflow

### ISSUE THREAD

**Issue by geochri** [markf6/pycorr_iceflow#1]
How can we use this ?
The demo project works well.
I am getting this error when I am trying to use Sentinel2 L2A from scihub.copernicus.eu.
```
pycorr_iceflow/pycorr_iceflow_v1.1.py", line 1123
ValueError: zero-size array to reduction operation minimum which has no identity

```
Can you help me with the workflow ?

Thank you.

**Comment by markf6** [comment]
Can you post the command line used for the run that generated that error, and if possible, the URLs for the two input images?

**Comment by geochri** [comment]
The scihub links are:
`https://scihub.copernicus.eu/dhus/odata/v1/Products('f67a5877-4760-407f-b348-e775a37ad155')/$value
https://scihub.copernicus.eu/dhus/odata/v1/Products('a86cb662-0f6d-44a9-ac85-cc135dd51250')/$value`

the Band8 for these images are:
`
https://we.tl/t-O17vwjwsgU
`

command line:
`python pycorr_iceflow_v1.1.py -imgdir .  S2B_MSIL2A_20230125T082129_N0509_R121_T37SBA_20230125T101549_B8.tif S2A_MSIL2A_20230209T082111_N0509_R121_T37SBA_20230209T115254_B8.tif -img1datestr 20230125 -img2datestr 20230209 -datestrfmt "%Y%m%d" -inc 10 -half_source_chip 10  -half_target_chip 55 -plotvmax 25 -log10 -out_name_base L2A_S2BA_MSIL2A_15_20230125_20230209 -progupdates -use_itslive_land_mask_from_web`

error:
`Traceback (most recent call last):
  File "pycorr_iceflow_v1.1.py", line 1128, in <module>
    test_for_masked_pix=np.min(img1_data_mask[(r_j_1[j]-half_source_chip):(r_j_1[j]+half_source_chip),(r_i_1[i]-half_source_chip):(r_i_1[i]+half_source_chip)])
  File "<__array_function__ internals>", line 200, in amin
  File "/home/r/anaconda3/envs/test_pycorr_env/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 2946, in amin
    return _wrapreduction(a, np.minimum, 'min', axis, None, out,
  File "/home/r/anaconda3/envs/test_pycorr_env/lib/python3.8/site-packages/numpy/core/fromnumeric.py", line 86, in _wrapreduction
    return ufunc.reduce(obj, axis, dtype, out, **passkwargs)
ValueError: zero-size array to reduction operation minimum which has no identity
`

**Comment by markf6** [comment]
Download full resolution images
Available until Mar 17, 2023
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAdh69Wjt2qt27ljNkCHmLPka3wCSAXPRbeFEGMAL0SCUsqsku9eL71FB%2F%24%7Bf%7D%3Fo%3DAl-Y-YvNyL-G6kU37BLu14jBHXZbNUwIMip6KX_dmko0%26v%3D1%26x%3D3%26a%3DCAogoVjRAKj4b7jszbiY-_8KfmshNlXFyZFD5rH6_VkodZUSdBDap8Ww5TAY2rfAhO8wIgEAKgkC6AMA_3RaIV5SBBrfAJJaBIvvUUFqJPV227gLMTImOGCv6PFr8Qi8b09sRQJln7CUf4rzqb7OQFLHNnIk_rC4JSQsDz-zGXy2_LSm_IjUlW-ceA3SyHN1z0xnxD3gQW8o%26e%3D1679073221%26fl%3D%26r%3DEBFC9B7B-6C57-49A5-9AD0-F95E4FAB759A-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3DF492E5B8-AEB1-4612-AD69-8081A1BA7F49%26p%3D120%26s%3DE-ZeIt6rCMQ2TrneiyqUq3tUN9k&uk=Tea4CWE9prAakm8eB1-H_A&f=Images.zip&sz=4830914>Hi George,

Thank you for forwarding the images and command line. 

The issue you are having happens because the images you are using are not single band images - gdalinfo reports them as having 4 bands - red, blue,green, and an alpha band.  If you use just band 8 from those two acquisitions pycorr runs to completion. 

Pycorr was put together to follow ice motion and report it as a rate - for mapping the displacement from an earthquake as you are trying, there are several things you can do to get more useful results.  

1) Since pycorr will divide the displacements it finds by the time between the two images as reported in the date fields, you can get total displacement in meters by giving the code two dates that are one day apart, rather than the dates of the images (pycorr will then divide the displacements in meters by 1 day, and so report total displacement in meters rather than the average displacement over the time interval between the two scenes).  Also, it may help to not use the “-use_itslive_land_mask_from_web” parameter -  this parameter will cause pycorr to try to zero out average displacement over ground (this is done to remove offsets between the two satellite images at the sub-pixel level - it is common to see images that are shifted by 10 meters or so because of imprecise knowledge of the satellite location and pointing; when mapping glacier flow we set the bare ground offset to zero to compensate for this.)

2) the total displacements you should see from that earthquake are <20 m, which is only 2 pixels from Sentinel 2 imagery - so you can speed up processing by using a smaller target chip size ( a 10 pixel source and 55 pixel target half size would track displacements of up to 45 pixels, or 450 m).

I pulled the band 8 images for those two acquisitions from the AWS Sentinel 2 L2A cog collection used in the example on GitHub - I have attached the output .nc file. The displacement shows up clearly, as do several bands of offsets related to the imaging sensors (banding with even edges).

Using:
python pycorr_iceflow_v1.1.py -img1dir S2B_37SBA_20230125_0_L2A -img2dir S2A_37SBA_20230209_0_L2A B08.tif B08.tif -img1datestr 20230125 -img2datestr 20230126 -datestrfmt "%Y%m%d" -inc 10 -half_source_chip 10 -half_target_chip 25 -plotvmax 7.5 -log10 -out_name_base L2A_S2BA_MSIL2A_15_20230125_20230209_meters_v2 -progupdates

I get:
￼


Click to Download
 <https://www.icloud.com/attachment/?u=https%3A%2F%2Fcvws.icloud-content.com%2FB%2FAcXWNX2gHD41z64hwx9u6wZt6FJMAfXjJ05YU9Puk9lGLsIPWF6ik0Mz%2F%24%7Bf%7D%3Fo%3DAjrGnX3Xkr3o9erIE_i4k2i8xFNQaJ_orQLWZMZQus7s%26v%3D1%26x%3D3%26a%3DCAogKohVZHmPU-AuftqebCva0Fb52hFCucNGGA5s6JSsEdgSdBDkqcWw5TAY5LnAhO8wIgEAKgkC6AMA_xYbdH9SBG3oUkxaBKKTQzNqJOWrRgoRoTkWKeOmVHJxRa1wfcIHyyfPnbZz8DvCe5CKwV7PY3Iku98_oGm4bRxtSKTdkMYKjA9F1Ztlv9jnZsg7U5abRqDh1zGk%26e%3D1679073221%26fl%3D%26r%3D54C8FB25-A494-4510-B9F3-20EE3CD4EDDD-1%26k%3D%24%7Buk%7D%26ckc%3Dcom.apple.largeattachment%26ckz%3DF492E5B8-AEB1-4612-AD69-8081A1BA7F49%26p%3D120%26s%3DmInTe4xMnNIRzz_Pw0obSn2zlHs&uk=mlpG596yMMyRvXJCFn1c3w&f=L2A_S2BA_MSIL2A_15_20230125_20230209_meters_v2_hp.nc&sz=35073588>L2A_S2BA_MSIL2A_15_20230125_20230209_meters_v2_hp.nc
35.1 MB

Mark

**Comment by geochri** [comment]
Thank you Mark for the instructions. Indeed, it was my mistake with the multiple bands. Everything is working perfectly. I have one more question. I understand that the  vx_masked and vy_masked vectors refer to the east-west and north-south motion components. The vv_masked speed in which direction refers to? Also the tiff output is the vv_masked speed?

George

**Comment by markf6** [comment]
The vv is simply the speed (or in this case the displacement magnitude) - the square root of (vx^2 + vy^2)

Note that the zero displacement value for both vx and vy can contain an offset that is due to each image having a geolocation error - one way to correct for this is to choose a far-field area in the two images to be zero displacement, and then subtract the average (or median) vx and vy values in that area to the offset fields. In the image pair you were looking at, the smallest offsets appear to be just west of the fault - you may want to select a reference area farther away from the deformation to set zero values.

**Comment by geochri** [comment]
Thank you Mark! I will also apply the step you suggested for the
geolocation error.
